### ISSUE TITLE
Update 1.0.2 throws an exception while adding as an extension to Unity container.

### ISSUE THREAD

**Issue by TheAifam5** [unitycontainer/microsoft-logging#1]
After the update to 1.0.2, application crashes on "AddNewExtension". Version 1.0.1 works.

Log:
```
Exception thrown: 'Unity.Exceptions.ResolutionFailedException' in Unity.Container.dll
An unhandled exception of type 'Unity.Exceptions.ResolutionFailedException' occurred in Unity.Container.dll
Resolution of the dependency failed, type = 'Unity.Microsoft.Logging.LoggingExtension', name = '(none)'.
Exception occurred while: Calling constructor Unity.Microsoft.Logging.LoggingExtension().
Exception is: MethodAccessException - Attempt by security transparent method 'Unity.Microsoft.Logging.LoggingExtension..ctor()' to access security critical method 'Microsoft.Extensions.Logging.LoggerFactory..ctor()' failed.
-----------------------------------------------
At the time of the exception, the container was: 
  Resolving Unity.Microsoft.Logging.LoggingExtension,(none)
  Calling constructor Unity.Microsoft.Logging.LoggingExtension()
```

Regards,
TheAifam5

**Comment by ENikS** [comment]
Please provide unit test to replicate the issue

**Comment by rlmartins76** [comment]
I am facing the same issue when updating to 1.0.2.

**Comment by ENikS** [comment]
It would be more helpful if you could post a unit test with failing code. 

The exception you posted is related to platform incompatibility. I have working [example](https://github.com/unitycontainer/examples/tree/master/src/Logging/Microsoft.Logging) here. Please check if you could run it and if you are following the same pattern.

**Comment by rlmartins76** [comment]
I checked your example, but it looks like you are referencing version 1.0.1 instead of the latest version 1.0.2.
The issue appears when version 1.0.2 is used.

<PackageReference Include="Unity.Microsoft.Logging" Version="1.0.1" />

**Comment by TheAifam5** [comment]
@ENikS Unit Test below. Please check also your example, you should reference the latest version.

```
using FluentAssertions;
[...]
Action addExtensionAction = () => new UnityContainer().AddNewExtension<LoggingExtension>();
addExtensionAction.Should().NotThrow();
```

**Comment by TheAifam5** [comment]
@ENikS any update for this issue?

**Comment by ENikS** [comment]
Been swamped with real life stuff and did not have chance to look at it. Does anyone want to submit a pull request with the fix? It should be simple project attribute change.

**Comment by ENikS** [comment]
Fixed
