### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by emanueldejanu** [unitycontainer/microsoft-logging#2]
Hi,

I was wandering why this library is using [assembly:SecurityTransparent] because it gives me the following error when starting an ASP.NET MVC 5 application:

`Attempt by security transparent method 'Unity.Microsoft.Logging.LoggingExtension..ctor(Microsoft.Extensions.Logging.ILoggerFactory)' to access security critical type 'Microsoft.Extensions.Logging.ILoggerFactory' failed`

Regards,

Emanuel

**Comment by ENikS** [comment]
What should it use?

**Comment by bjorn-ali-goransson** [comment]
Same here. Had to downgrade. If you clone my repo and upgrade to 1.0.2 you should be able to reproduce it. Do you want those details?

**Comment by bjorn-ali-goransson** [comment]
Duplicate of https://github.com/unitycontainer/microsoft-logging/issues/1

**Comment by ENikS** [comment]
Duplicate of https://github.com/unitycontainer/microsoft-logging/issues/1
