### ISSUE TITLE
Support for ILoggingBuilder

### ISSUE THREAD

**Issue by marxxxx** [unitycontainer/microsoft-logging#4]
Hi,

will you update your library to support ILoggingBuilder as LoggerFactory is getting deprecated in version 2.2 of Microsoft.Extensions.Logging ?

see this: https://github.com/aspnet/Extensions/issues/615

Thank you!

**Comment by ENikS** [comment]
Would you like to help with update?
You could send a PR. I could do it myself, but it will take a while

**Comment by marxxxx** [comment]
I figured out that no change to your library is actually necessary because with a Microsoft.Extensions.Logging version >= 3.0.0.0 there will be a LoggerFactory.Create method that can be used in combination with ILoggingBuilder.

**Comment by OskarKlintrot** [comment]
IMHO this should be reopened since using the `ILoggingBuilder` is the preferred way to configure the logging and add providers etc. Not a deal breaker but more of a nice-to-have :)

**Comment by ENikS** [comment]
@OskarKlintrot 
Do you want to take care of this too, before I release the latest?

**Comment by OskarKlintrot** [comment]
I'm not sure how to solve it, especially not without using `Microsoft.Extensions.DependencyInjection` which feels a bit bloated, would be nice to manage only with `Microsoft.Extensions.DependencyInjection.Abstractions`. Unfortunately I don't really have the time to solve it 😞 Feel free to make a new release! 👍

**Comment by ENikS** [comment]
The idea was to use it without DI
> Use ILogger without dependency injection

How Unity can help with it? What am I missing?
