### ISSUE TITLE
Register ILoggerFactory

### ISSUE THREAD

**Issue by OskarKlintrot** [unitycontainer/microsoft-logging#5]
I noticed that the extension doesn't register `ILoggerFactory` despite that Microsoft's documentation says that it's a valid use case to inject the factory to be able to [explicitly specify the log category](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#log-category). Maybe the instance of the factory could be registered as well?

**Comment by ENikS** [comment]
It is a good suggestion. Would you like to send a pull request?

**Comment by OskarKlintrot** [comment]
I could give it a try! What would make sense to (unit) test? Only that it can get resolved or something else?

**Comment by ENikS** [comment]
I think getting the factory should be sufficient
